# Generated by Django 5.0.6 on 2024-07-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
